### ISSUE TITLE
Backgrounds still offset in 0.81?

### ISSUE THREAD

**Issue by Ser-Noodles** [Lyall/Disgaea5Fix#1]
Hi, sorry not sure if you'll even see this as I know you're hard at work on other games. Thanks so much for doing these fixes!

I notice in the changelog for v0.81, it says it fixes the offset backgrounds. Unfortunately I'm still having this issue.

Maybe it's something I'm doing my end? But I'm not sure what.

![{1A503803-B5C1-4BD3-B60E-5DFA251A758E}](https://github.com/user-attachments/assets/62db89cb-b6c1-4f77-abe0-2adf2a13f75e)

The main menu does seem to be fine
![{5EAE8D96-2264-4644-9292-A7D43D42A344}](https://github.com/user-attachments/assets/00f74db4-654c-4f8d-8b0d-60c6437a5957)

But anything with a still background like the opening monologue or the talking segments the background is aligned to the left not the center.
![{0B1D148E-698E-4707-A1C9-2AF43CFF4BB6}](https://github.com/user-attachments/assets/939a3388-9347-44c2-b8da-3248f35f6d3d)
![{6CC999E1-59C4-4EBE-99D9-E73FC161C3E5}](https://github.com/user-attachments/assets/cc4d2438-da40-41a0-8cc4-1627a8451f14)

Although the hub seems fine, which is strange?
![{02BF4413-0356-40DE-9B30-9E660CE3322B}](https://github.com/user-attachments/assets/80b0e353-75ba-4aa5-9294-64a2fb3108ce)

**Comment by Lyall** [comment]
If I recall correctly the backgrounds are actually somewhat fixed with that code. There are some that are centered by default and some that are aligned-left. The last screenshot you posted of a dialog scene for example, is offset without the fix in place. I think the issue was that there is no obvious way to distinguish between backgrounds that will center and backgrounds that are left-aligned, so I can either fix one type of background or the other. At least until I can find a way of identifying "justification" of the backgrounds, if that's possible.

**Comment by Ser-Noodles** [comment]
No worries, I'll continue playing it in 16:9 until I've beated the story then. The actual gameplay itself works perfectly.

Thanks again!
